---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jaime.
--- DateTime: 2021/2/22 下午2:52
---
local mem = collectgarbage("count")

local gc = function()
    print("------begin------")
    local remain_main = collectgarbage("count") - mem
    print(remain_main)
    print("------end------")

end

function timer()
    collectgarbage('collect')
    performwithdelay(gc,1000)
end


function main()
    print(collectgarbage("count"))
    local t1 = "qwertyuiopasdfghjklzxcvbnm1234567890123411"
    t1 = 's' .. t1
    print(collectgarbage("count"))
    return t1
end